### ISSUE TITLE
Search/filter function

### ISSUE THREAD

**Issue by hackily** [PredixDev/px-table-view#1]
Hey there! Great work on this component! 

Do you think you could create a search/filter component for the table as well?
I have a use case where px-data-table would be overkill, but there would be too many rows to fit onto the screen without scrolling if I'm using px-table-view.

I'm envisioning a component with properties that you can enable to search the title, body, and/or the labels.

Thanks!

**Comment by mdwragg** [comment]
Hi, thanks very much!

That component does sound useful. Do you have a sketch that explains what you're thinking?

Thanks.

**Comment by mdwragg** [comment]
(I should also say, the thanks should be directed at @jonniespratley - all his fine work :-)

**Comment by hackily** [comment]
Sure! I'm aiming for something that may look like [this](http://imgur.com/dWu39Yg).

While that snapshot is more aimed towards mobile, I think a search field taking up the entire row wouldn't look altogether terrible for a full desktop sized screen either, like [so](http://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_filters_tables)

My thought is that by default, filtering would work for all the text fields - Title, subtitle, body, label1 and label2. 

However, if the developer wants the user to only be able to search through a subset of the text fields, they would be able to include parameters like so: `<px-table-filter filter-by="{"title","body"}">`, where _filter-by_ would take an object containing strings matching the text fields of the table rows.

**Comment by jonniespratley** [comment]
Hi @unkani,

If you want to perform various list functions I would suggest using the great `iron-list` component with the `px-table-view` component. This component is not intended to do the heavy lifting of filtering and such, this component is more or less the `aesthetics` with some nice utilities.

For some heavy lifting list rendering/sorting/filtering, etc. I would implement iron-list for the logic, and px-table-view for the visual. Take a look at this bare bones example using iron list. 

[iron list example](http://predixdev.github.io/px-table-view/bower_components/px-table-view/demo/iron-list-demo.html)

If this is no help, pull requests are always welcome ;).
